### ISSUE TITLE
Contact point contains an Identifier

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#15]
Found at [output](https://github.com/OP-TED/ted-rdf-mapping-eforms/blob/01f8f5907157c32643d09ca1af56bda206b7cbe9/mappings/package_cn_v1.9/output/sdk_examples_cn/cn_24_open_accel/cn_24_open_accel.ttl#L549)

However, Model v.4.0.0 does not mention identifiers for Contact Points. Is it the model or the data?

![](http://www.plantuml.com/plantuml/img/fLH1QiCm4Bph5SB7G49xrQ4aBHGCfJ61daeFMsdZ26J9I4f8MlBtMcvSsx4h5thqxknuPdOHMJeFrkyBHRW2vsYY3DTi9OH5vnBwISYPD2qi3RlVdz26EgNXKseXENXqgJuOoH4VZFR0VMQazfHHNfe3wzKwV8Dcoxi3TsayGu4LaHLRbYcG-abwjA3ewyrYSVlMmX_X-1ji5c3rppmgB7T6OnGgk6S27RUozDBeQLeiGAeex28orLLTex_aMuqSdM2WJo-Rj7LKhm1-8DsDDA0sH6DpjhOvQFa1GMqlmypA0knfSYcjdGEpc4jNoKInYagOrbap1drk_zwLkDvMw6lTpKJ_t5OvQf_gZL4uTXor-kzspDUPZDtQV7v7a-0bkRvwrhD6HZ9kPcV9w1cpo0B8qDXVsOQkOzh6V8tjTyhVVx8PTjduHP3kwn8O8ab47nsoH2t2U_O5)

**Comment by schivmeister** [comment]
Indeed, @cristianvasquez, your observation is correct. @csnyulas had raised a concern about this, but we chose to commit this nonetheless as (i) the relevant field [OPT-201-Organization-TouchPoint](https://github.com/OP-TED/eForms-SDK/blob/8b4f177cc5c797508179f100ea9749776efeb693/fields/fields.json#L38757) name is _TouchPoint Technical Identifier_, and (ii) there is a [corresponding scheme attribute](https://github.com/OP-TED/eForms-SDK/blob/8b4f177cc5c797508179f100ea9749776efeb693/fields/fields.json#L38763) for it (which is in turn represented by `epo:hasScheme` through an `epo:Identifier`). The eForms SDK in this case took precedence, but we can agree to be compliant with ePO instead and omit it. Please discuss amongst your team and let us know.
