### ISSUE TITLE
Lot epo:hasAmountValue 

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#17]
I found an Instance of epo:hasAmountValue attached to an epo:Lot but there is no mention of it in v4.0.0. I suspect it should be epo:hasEstimatedValue is that the case?

![image](https://github.com/OP-TED/ted-rdf-mapping-eforms/assets/361916/6f9d5faa-0392-45f0-9d35-f5e0943c05da)

![](http://www.plantuml.com/plantuml/img/hLTBRnen4BxlhrXnZ4HKhbPLXIIaGY8g2aalKG_6En2tNflwGHEr_U-r2R2xtjd5QNjZxV4txs-6xC9OggqhHSO4DIOVm4QHAoKP6CELd1ZBIsfXaF_CyZpSFL5pE2mktGleIlWEjY0Tv6GdUAiaUEoNprJuiyTtv-UZBmZ6W_bRYBQLnQjWp-FVMTtF6oUBu5bqF5CMEPqBAYKKSwsOqr22j7CVkIemAwN109YQmAVbLs1sRq_xlE7GuVazi2V9ln_TgBw3-5diGa25mkCsCbJJjM1g0zTyomiefj8gxzmUEVnw766OJc-K0IG62wjzcDUSrHGWOaURaRj6MWxtFkTbFg1sk5MC25XJCLnImmsAhKlaUBpsfapbdHArI30bBJnRHmKtlbfVUZE1XhOXLW5pixYTB1otT2b2efvDGPRAwwQocLLk7WoNwyb3A3NJBta7Nftsslh4V78FSWokmJ3DDzQtW7-ZYrKeKYvdt8Ac8iQ_KblG8GmVv-CJAiP5mGCg5LFf2zFtLe-Aizh3MSZTPKXTWcrdbMqBjulmlGhfFLQ-_nahsDVc8PFxhyZJ4EnQliDd4-ZGR9v2V4KpkzW0uolEQjhHgsvt_Qjs-KPAdLXn8GpMH7kbw5LBANMIFTreMi8FfR-DrnfsWhVqcPUkFCc1hq3E971DArfxmgrY534mphDOB366hPoUY2Etj4T60ijtDV3xNyDXJ9nPf_AcT1Cggx5H9OTwcc1D63b9Tk13g5F3SFWX7uHS3khiIR2kEuan6aJZWKHDcMp5wzmbKRScFyVBYPpixAntZhVSR1j2-WTzTm9Zx6W84hp4amA23KtIvgSitXPs6ACggBkbXwGj45ddblXcH_4LyZygGFVBv5B35nvoai-pzb8IGtVMLxor93TcLonI1iOR6EIusv7s84bhiKwirXASx3jMAwHZUlrxTNNzzSWkG1RXpzGV)

I'm attaching the sample turtle

[00189213_2024.txt](https://github.com/OP-TED/ted-rdf-mapping-eforms/files/15500468/00189213_2024.txt)

**Comment by schivmeister** [comment]
@cristianvasquez thanks for spotting these issues, indeed you are right, this should've been the object property `epo:hasEstimatedValue` and the datatype property `epo:hasAmountValue` crept in by human error (it appears both as the relationship and as the attribute of the linked object).
