### ISSUE TITLE
Testing SHACL with inherited properties

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#18]
Hi @schivmeister,

I hope you're doing well.

I've been working on the transformation outputs, and it seems some bugs have slipped through. The SHACL engine appears to be ignoring inherited properties. I understand no reasoner is in place, but we can try explicitly appending triples for the inherited properties.

I've appended some in a branch for you to review: https://github.com/OP-TED/ted-rdf-mapping-eforms/blob/72e3455b67182f95498304d8ddc320a314e7274a/mappings/package_cn_v1.9/validation/shacl/epo/ePO_core_shapes.ttl#L5357

These elements were generated using the following CONSTRUCT query over the dataset:

```sparql
PREFIX shacl: <http://www.w3.org/ns/shacl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?childShape shacl:property ?parentProperty .
}
WHERE {
  GRAPH ?g {
         ?child rdfs:subClassOf ?parent .
         ?parentShape a shacl:NodeShape ;
            shacl:targetClass ?parent ;
            shacl:property ?parentProperty .
          ?childShape a shacl:NodeShape ;
          shacl:targetClass ?child .         
  }
}

```
I propose running a SHACL validation with these inherited properties included to see the results.

Please let me know your thoughts or any other suggestions you have.

Cristian

**Comment by cristianvasquez** [comment]
I made a mistake, is rdfs:subClassOf* (transitive)

```sparql
PREFIX shacl: <http://www.w3.org/ns/shacl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?childShape shacl:property ?parentProperty .
}
WHERE {
  GRAPH ?g {
         ?child rdfs:subClassOf* ?parent .
         ?parentShape a shacl:NodeShape ;
            shacl:targetClass ?parent ;
            shacl:property ?parentProperty .
          ?childShape a shacl:NodeShape ;
          shacl:targetClass ?child .         
  }
}
```

**Comment by schivmeister** [comment]
@cristianvasquez indeed, this is a general problem with SHACL validation. doing the validation with inference can lead to unwanted behaviour, depending on the implementation. there are, however, certain constructs in SHACL extensions that allow such validations without inference, but I cannot vouch for them as we have not evaluated them, and model2owl is not aware of them (which generates ePO artefacts including the SHACL shapes we include and modify in this project).

thanks for this technique, I generally find no fault in this workaround, as we are already working around the other issues. please confirm that this helps to suppress those false positive violations.

**Comment by schivmeister** [comment]
An update to this: we decided to check again the effect of inference with a SHACL engine, specifically for the use case of eForms, before incorporating these changes (keeping a modified SHACL file up-to-date may become a maintenance burden, so it would of course be best if we can avoid such modifications altogether).

**Comment by schivmeister** [comment]
> An update to this: we decided to check again the effect of inference with a SHACL engine, specifically for the use case of eForms, before incorporating these changes (keeping a modified SHACL file up-to-date may become a maintenance burden, so it would of course be best if we can avoid such modifications altogether).

We investigated the result of inference and found that just the inclusion of referenced ontologies (ePO, Time) in the SHACL validation graph greatly reduced false positives, and yielded no side-effects, as was initially suspected.

For PySHACL:

```python
    input_data = Graph()
    input_data.parse(data_file)
    input_data.parse(ont_file1)
    input_data.parse(ont_file2)
...
    _, _, text = validate(input_data, shacl_graph=shacl_data, inference="rdfs")
```

We therefore chose to not implement the proposed changes here.
