### ISSUE TITLE
multiple locn:fullAddress

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#19]
I found an instance of locn:fullAddress containing 3 values. 

![image](https://github.com/OP-TED/ted-rdf-mapping-eforms/assets/361916/527e8a68-8eae-4ed5-8ba1-58f7f13c5f24)

Please consider concatenating them into one value

Attached sample
[00082127_2024.txt](https://github.com/user-attachments/files/15574362/00082127_2024.txt)

**Comment by schivmeister** [comment]
Thanks @cristianvasquez, we found this out too looking at the output that you shared for the other tickets.
