### ISSUE TITLE
missing isSubjectToProcedureSpecificTerm

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#37]
The model declares that a Procedure needs at least one value for `epo:isSubjectToProcedureSpecificTerm` but is missing.

source: https://ted.europa.eu/en/notice/127182-2024/xml

![image](https://github.com/user-attachments/assets/d74c7bf8-8dec-4e88-8151-f4aad884c5b6)

**Comment by muricna** [comment]
I think the cardinality needs to be relaxed to 0..1, the ticket should be transferred to ePO

**Comment by cristianvasquez** [comment]
Closed in favor of: https://github.com/OP-TED/ePO/issues/680
