### ISSUE TITLE
missing epo:hasAwardCriteriaStatedInProcurementDocuments RML mapping

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#42]
Hi, 

The model declares that hasAwardCriteriaStatedInProcurementDocuments is mandatory, however, I could not find a mapping for it. The following [search](https://github.com/search?q=repo%3AOP-TED%2Fted-rdf-mapping-eforms+path%3A%2F%5Emappings%5C%2F%2F+hasAwardCriteriaStatedInProcurementDocuments+language%3ATurtle&type=code&l=Turtle) finds the term only in the SHACL files

**Comment by muricna** [comment]
I think the cardinality is wrong I think it should be 0..1.  The issue should be transferred to ePO.  Furthermore this concept is not used in eForms.

**Comment by cristianvasquez** [comment]
Closed in favor of: https://github.com/OP-TED/ePO/issues/679
