### ISSUE TITLE
missing epo:hasMainActivity for epo:Buyer

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#43]
The following notice:
 
HTML: https://ted.europa.eu/en/notice/-/detail/137599-2024
XML: https://ted.europa.eu/en/notice/137599-2024/xml

misses a `epo:hasMainActivity` value for the Organization 'Fountain Fuel B.V.'

Data: 

`<cbc:ActivityTypeCode listName="entity-activity">gas-heat</cbc:ActivityTypeCode>`

**Comment by muricna** [comment]
The codes seem to be associated with the values used for Directive 2014/25/EU (Utilities) however in this case the Legal basis is "other"
