### ISSUE TITLE
Omit locn:Address if not specified in the data

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#45]
Hi, 

Looking at the example notice 127505-2024 we can see it specifies only a country and not an address. 

The RDF produced looks currently like this: 

![image](https://github.com/user-attachments/assets/008c24cf-7642-4617-a998-341310d958b4)

We think that instances of `locn:Address` should be omitted when they are not specified and have only `dct:Location`

Source: 

xml: https://ted.europa.eu/en/notice/127505-2024/xml
html: https://ted.europa.eu/en/notice/-/detail/127505-2024

**Comment by schivmeister** [comment]
It was agreed that we would have address information replicated in both the Location and Address, and according to the CM, we interpret also the geocodes as first-class citizens as part of this notion. Please consider giving this another thought.

**Comment by cristianvasquez** [comment]
Thank you for pointing this out, at first glance I was confused about the replication, it felt not right. I opened a new issue in ePO for further discussion: https://github.com/OP-TED/ePO/issues/682 

Regarding the mapping, I agree with your suggestion. So I'll close the issue.

While it may be challenging to identify places of performance that lack an address, keeping the values will be safer for applications that calculate indicators through queries since ePO allow country code in both `dct:Location` and `locn:Address`.
