### ISSUE TITLE
Clarification needed regarding the mapping of `ND-Lot` (Question 5)

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping-eforms#5]
**Field ID:** ND-Lot
**Name:** -
**absolute XPath:** `/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']`

**Comment:** We believe that this is the best place to link Lot to Procedure. However, there is no explicit information in the data that can be used to make this link. (id of lot not referenced from the `cac:ProcurementProject`, and id of procedure not referenced  from `cac:ProcurementProjectLot` XML elements)

**Potential Mapping:**

- **Class Path:** `epo:Procedure / epo:Lot`
- **Property Path:** `?this epo:hasProcurementScopeDividedIntoLot ?value .`

**Comment by muricna** [comment]
Indeed in the xml Competition Notice it is implicit that the Procedure is made up of the Lots defined in the Notice.  However this is not the case in the Result Notices separate Result Notices can be used for one or more of the lots within a given procedure.

For the **Competition Notices**, we think this can be added in the absence of any other predicate.  Would this predicate be instantiated in the case of just one lot it would probably be advisable? However in the case of **Result Notices** we have reservations.  We **are also not sure that this is a mapping of a node but an additional predicate to add clarity**.

The ePO needs to provide a clear definition of this predicate and consider whether future versions of the ontology (not covered by this mapping exercise) whether another predicate should be implemented, we will create an ePO issue.

**Comment by schivmeister** [comment]
@muricna @cristianvasquez @nhajlaoui has an ePO issue for this been created?

We understand that this mapping is OK for Competition Notices, and that there are reserves about **Result Notices**. However, given that this is not covered by ePO 4.0, which is in our current scope, are we in agreement to include this mapping for the Result Notices? If not, do you have an alternative recommendation for linking the Lots to the Procedure in a Result Notice?

**Comment by cristianvasquez** [comment]
I read the issue a few times, but I'm not sure about what is the question.

Is it how to relate a procedure with a lot?

I understand that lots can only exist connected to a procedure in this way: 

```
:someProcedure a epo:Procedure .

:someLot a epo:Lot .

:someProcedure epo:hasProcurementScopeDividedIntoLot :someLot .
```

![](http://www.plantuml.com/plantuml/img/ZLAz2i8m4Dxp5A6ZaA9h42de8WWAxLOSQdfYf6rAahgexwwfWTJOsewvVFVzt1sAbCwaRie2iI9J2WTG2xeJEgw1yJDd2SWom7U4diX3c2h6vg4-M507ALWZeOHAhoNN8BceC6qnlL_fF0ndHyl2LToShi1q8ZnzI-5NRVUtCQC3-Ll9sRjaNMCn4pLi-8tda6yhRRGSFquN0vo-zvwPT63xDeZ537qk7uJufYU0pUYHdvMG5GwCzw2p7pejFd8TBStSqVGdf-DR_yFvSrnqPFqeWYet5_e2)

Now suppose your URI patterns are: 

<http://our-domain/resources/procedure/{procedure_global_id}> for procedures

<http://our-domain/resources/procedure/{procedure_global_id}/lot/{lot_relative_id}> for lots

Then the triple would be:

```
<http://our-domain/resources/procedure/{procedure_global_id}>   epo:hasProcurementScopeDividedIntoLot <http://our-domain/resources/procedure/{procedure_global_id}/lot/{lot_relative_id}>
```

Or this is more about lacking data?

**Comment by schivmeister** [comment]
@cristianvasquez you describe exactly the mapping (`:someProcedure epo:hasProcurementScopeDividedIntoLot :someLot .
`) we ask about in this question, to which @muricna replied implying that it is OK for Competition Notices but likely not for Result Notices, however ePO needs to be adjusted to add clarity over this predicate or introduce new ones for such connections. If relevant tickets have been filed as @muricna intended to, we can close this.

**Comment by cristianvasquez** [comment]
I see what is the problem. I created a new issue: https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/33

Regarding the lots in Competition Notices, these can be mapped but commented out in the meantime. Or any other suggestion? 

We need to keep track somewhere these predicates.

**Comment by cristianvasquez** [comment]
Dear @csnyulas I've discussed about the path for Result Notices

`?this epo:hasProcurementScopeDividedIntoLot ?value .`

we can use this path in the meantime for Result Notices, where each Result Notice is linked (or scoped) to the corresponding lots
