### ISSUE TITLE
Document special URI policy exceptions as SHACL shapes

### ISSUE THREAD

**Issue by schivmeister** [OP-TED/ted-rdf-mapping-eforms#50]
> Regarding the documentation I propose we maintain the documentation for the general case, and write down a SHACL document that focuses solely in documenting how URIs are formed for exceptional cases. We can use this document to trace the rationale behind our URI choices.
> 
> ```
> epo:ReviewerShape a sh:NodeShape ;
>     sh:targetClass epo:Reviewer ;
>     rdfs:comment "We found identify reviewers in the following way...." ;
>     ex:github <https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/31> .
> ```
> 
> In the future we can expand this documentation to include patterns for the important classes, and validate URIs. For example, this would document how the ex:Movie URI looks like:
> 
> ```
> ex:MovieShape a sh:NodeShape ;
>     sh:targetClass ex:Movie ;
>     rdfs:comment "We found that movies are entities that..." ;
>     sh:property [
>         sh:path sh:targetNode ;
>         sh:pattern "^http://example.org/resource/movie/[a-zA-Z0-9\\-]+$" ;
>         sh:message "The movie URI must start with 'http://example.org/resource/movie/' followed by alphanumeric characters or hyphens." ;
>     ] ;
> ```
> 
> In summary, let's adopt that URI pattern, and create a SHACL document that documents exceptions. Should we put this close to the documentation?

_Originally posted by @cristianvasquez in https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/31#issuecomment-2284193169_

**Comment by cristianvasquez** [comment]
In the meantime, I won't add the URI policy file since I misunderstood how `epo:Reviewer` URIs are formed. 

For example at: 
```
epd:id_a190353f-8557-4b1d-ad00-b3db8604a7fc_Reviewer_Lg96o4u3Pe2t4SkoPaxEB3 a epo:Reviewer;
  epo:contextualisedBy epd:id_a190353f-8557-4b1d-ad00-b3db8604a7fc_Lot_LOT-0001, epd:id_a190353f-8557-4b1d-ad00-b3db8604a7fc_Lot_LOT-0002,
    epd:id_a190353f-8557-4b1d-ad00-b3db8604a7fc_Lot_LOT-0003;
  epo:playedBy epd:id_a190353f-8557-4b1d-ad00-b3db8604a7fc_Organization_ORG-0004 .
```

I thought uniqueness was ensured by explicitly separated segments, but is a postfix hash such as `_Lg96o4u3Pe2t4SkoPaxEB3`, which is not a bad choice per se, but SHACL is not adequate to document the patter in this case.
