### ISSUE TITLE
Unconnected epo:MonetaryValue

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#57]
### Description

I found some orphan entities in the RDF, two `epo:MonetaryValue` and an `adms:Identifier` (no other entities connected to them)

![image](https://github.com/user-attachments/assets/2801afdf-d6df-4270-bcc9-e64fc0e34ebb)

### 191524-2024

- [HTML](https://ted.europa.eu/en/notice/-/detail/191524-2024)
- [PDF](https://ted.europa.eu/en/notice/191524-2024/pdf)
- [XML](https://ted.europa.eu/en/notice/191524-2024/xml)

**Comment by schivmeister** [comment]
I could not reproduce this. Please see if you produce the same output with a manual RMLMapper transformation. Note that the SDK version is 1.6, so use the rules from that CAN package, against the cited data file.

Output of a manual run tested with [Notice Viewer](https://check-v4-0-0.netlify.app/#):
<img width="842" alt="image" src="https://github.com/user-attachments/assets/e47e82b5-354a-4e54-973f-1665e1708a36">

I have attached the data and the reference output (which gives me different results in the Notice Viewer in terms of search results for `_MonetaryValue` 8 vs. 12 expected). Please remove the `.txt` extension.

[2024-OJS065-00191524.ttl.txt](https://github.com/user-attachments/files/17099279/2024-OJS065-00191524.ttl.txt)
[2024-OJS065-00191524.xml.txt](https://github.com/user-attachments/files/17099296/2024-OJS065-00191524.xml.txt)

**Comment by cristianvasquez** [comment]
Hello, this was a mistake on my side, apologies! 
I'm closing this issue
