### ISSUE TITLE
Organization to be declared as leader of the group

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#58]
Hi! The notice XML declares that the organization ORG-0005 is the leader of a group. 

```xml
	<efac:Tenderer>
		<cbc:ID schemeName="organization">ORG-0005</cbc:ID>
		<efbc:GroupLeadIndicator>true</efbc:GroupLeadIndicator>
	</efac:Tenderer>
```

The model 4.0 of the ontology declares a group is represented as follows:

![](http://www.plantuml.com/plantuml/img/ut8eBaaiAYdDpU5ApaaiBbPGoYzAj_8lIa_CownABCdCprDIgEPIK0295fSc8KlufobOAQ2hLeWsqDFJYkMgvOAPbrgG3rLH35RXNfHVMW0n52ILavgOubI9ooJ3MAYoZCHYtzJSfDGYh2eDeNPYSRnDZQukBaTmuNAShgwTWXB8UYLiuM65v73yHe3SXSS8kAUmEHpc1bm6O8qHBeVKl1HGP080)

However, I cannot find this in the RDF. Perhaps I'm missing something?

### 191514-2024

- [HTML](https://ted.europa.eu/en/notice/-/detail/191514-2024)
- [PDF](https://ted.europa.eu/en/notice/191514-2024/pdf)
- [XML](https://ted.europa.eu/en/notice/191514-2024/xml)

**Comment by schivmeister** [comment]
According to discussions related to the topic of tendering parties and tenderers, recall that we decided to interpret a group of tenderers only when there is more than one tenderer. In the case of this notice, that does not appear to be the case, i.e. there is only one tenderer. Therefore, I believe this is wrongly marked-up data, in that there is no meaning to the `GroupLeadIndicator` when there is just one tenderer and hence no group.

```xml
<efac:TenderingParty>
	<cbc:ID schemeName="tendering-party">TPA-0001</cbc:ID>
	<efac:Tenderer>
		<cbc:ID schemeName="organization">ORG-0005</cbc:ID>
		<efbc:GroupLeadIndicator>true</efbc:GroupLeadIndicator>
	</efac:Tenderer>
</efac:TenderingParty>
```

**Comment by csnyulas** [comment]
@muricna or @cristianvasquez can you please confirm that this is a "bad data" case (i.e. the data contains some statement that has no relevance and can't be represented in the RDF output), and that the fact that we are not mapping this value in this case is correct, and it is in accordance with what we discussed on the Aug. 28th clarification meeting, and with the conceptual mapping (cf. fields `OPT-300-Tenderer` and `OPT-170-Tenderer`).

**Comment by muricna** [comment]
This is not necessarily bad data the notice may just show the lead and not the members.  However this is from SDK 1.7 and since SDK 1.11 the Group leader  is only allowed and mandatory when there is more than 1 organisation.
Therefore to simply we will assume that the Group Lead does not need to be mapped when there is only one organisation shown for the Tenderer in the xml.
I therefore close this issue
