### ISSUE TITLE
Mapping of fields not mentioned in subtype specific JSON files

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping-eforms#6]
This is an issue that was raised in context of issue [Clarification needed regarding the mapping of OPT-090-Lot (Question 2)](https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/2)
 
More specifically, in the reply from @muricna : https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/2#issuecomment-1919188376 it was suggested that some additional fields that do not appear in the notice-type specific JSON files, such as `10.json` ... `24.json`, and which turned out to be attribute fields related to those fields, should also be mapped.
For the full context, please read the discussion on the original issue, up to (and including) https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/2#issuecomment-1935000295

The question that need to be investigated are:
- Is there a new definition of what fields are included in a specific notice-type, other than relying on the notice subtype JSON file?
  - If yes, what would be that definition?
- Are the additional fields only attribute fields?
- How should attribute fields be mapped:
  - in the Conceptual Mapping?
  - in the Technical Mapping?
- The meaning of some attribute fields translate well into meaning in EPO and/or RML (such as `Currency`, `Unit`, and `Language`), but others, like `List` and `Schema`, do not. What should we do about those?

**Comment by muricna** [comment]
You should find a solution where by the data provided in the xml notice is reflected in the corresponding RDF.

**Comment by csnyulas** [comment]
As discussed with OP, we came to an agreement to integrate attribute fields into the technical mappings, but the conceptual mappings of the attributes are not required.
