### ISSUE TITLE
Incorrect language tagging

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#66]
Instance: 127294-2024

- [HTML](https://ted.europa.eu/en/notice/-/detail/127294-2024)
- [PDF](https://ted.europa.eu/en/notice/127294-2024/pdf)
- [XML](https://ted.europa.eu/en/notice/127294-2024/xml)

The RDF includes langstrings with incorrect language identifiers—specifically, the Dutch and French labels are swapped.

![image](https://github.com/user-attachments/assets/752aae47-1dd5-4d8d-b59a-51fb25d950e5)

![image](https://github.com/user-attachments/assets/91dba92c-3acf-4229-8d62-cf8c24b89977)

![image](https://github.com/user-attachments/assets/b3199baa-7132-415a-ae84-dcc43dc42473)

The correct language information can be found in the languageID attribute, as shown below:
 
```xml
    <cbc:Description languageID="NLD">Vlaams Gewest</cbc:Description>
    <cbc:Description languageID="FRA">Région Flamande</cbc:Description>
```

```xml
    <cbc:Name languageID="NLD">Raamovereenkomst voor studiebureau "Asbest" voor het uitvoeren van inventarisaties,
        beheerplannen en jaarlijkse updates
    </cbc:Name>
    <cbc:Name languageID="FRA">Contrat cadre pour bureau d'étude "Amiante" pour réalisation des inventaires, plans
        de gestion et mises à jour annuelles
    </cbc:Name>
    <cbc:Description languageID="NLD">Raamovereenkomst voor studiebureau "Asbest" voor het uitvoeren van
        inventarisaties, beheerplannen en jaarlijkse updates
    </cbc:Description>
    <cbc:Description languageID="FRA">Contrat cadre pour bureau d'étude "Amiante" pour réalisation des inventaires,
        plans de gestion et mises à jour annuelles
    </cbc:Description>
```

**Comment by schivmeister** [comment]
This looks like a data problem. These elements should _not_ be repeatable [according to the eForms SDK](https://github.com/OP-TED/eForms-SDK/blob/af03a10e3f8182e7dc54bf283234cf719eb2e65e/fields/fields.json#L29300). The mappings were written and work correctly according to those definitions.

**Note:** This triggers a [known](https://github.com/RMLio/rmlmapper-java/issues/235) upstream tooling/technological (RMLMapper) limitation, regarding undefined and non-deterministic behaviour for non-standard mappings of multiple values at child elements (e.g. functions like this for language tags, advanced template/reference conditions).

**Comment by cristianvasquez** [comment]
I'm afraid is a misinterpretation. I did some inquiry and I can confirm that when the field is defined with a type of "text-multilingual" and is not repeatable, means it can only appear once per language, with different values for each language.

For example, the following is valid because each value is in a different language:

```
<cbc:Name languageID="NLD">Raamovereenkomst voor studiebureau "Asbest"...</cbc:Name>
<cbc:Name languageID="FRA">Contrat cadre pour bureau d'étude "Amiante"...</cbc:Name>
```

However, the following is not accepted because both entries are in French (same `languageID="FRA"`) with different values:

```
<cbc:Name languageID="FRA">Raamovereenkomst voor studiebureau "Asbest"...</cbc:Name>
<cbc:Name languageID="FRA">Contrat cadre pour bureau d'étude "Amiante"...</cbc:Name>
```

The same language cannot have two different values for the field.

I'm not familiar with the upstream RMLMapper limitation, Do you foresee any workaround to include multilingual fields?

**Comment by schivmeister** [comment]
You are right that we should be interpreting the repeatability with the context that that's the only way multilingual fields can be expressed in the source.

It is unfortunate, however, that (i) the SDK did not have that information explicitly encoded in some way (e.g. marking the language attribute itself as repeatable) -- which might've resulted in rules implemented for this differently -- and that (ii) at the same time, the RML language itself is underspecified for mapping multi-valued properties that go beyond the basics (language-tagged values in eForms being one case requiring advanced transformation with lookup tables).

It is not helpful to have different values with an incorrect language tag, but thankfully this affects only notices where content is expressed in more than one language.

The workaround basically requires extracting all language-related fields and putting them into their own mappings, which in the upstream ticket we refer to as the "unintuitive" approach, and is what we have finally chosen to implement.
